<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/Boolean_indeks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U7')

In [4]:
# data
data = np.random.randn(7,4)
data

array([[ 0.01403562,  2.37707277, -0.83516992, -1.5142136 ],
       [ 1.47152496,  1.64142057,  0.14316544, -0.14550955],
       [ 1.988348  , -0.01441726,  0.91414482,  0.54817747],
       [ 1.37572648, -1.55586994,  0.2507873 ,  0.65269808],
       [ 0.07802936, -0.52263526,  0.7971493 ,  0.5713412 ],
       [ 1.0423662 ,  0.97306909,  1.46000477, -0.18628596],
       [-0.15796344, -0.85404436,  0.60983204,  2.837151  ]])

In [5]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [7]:
data[names == 'Hasan'] # Hasanga tegishli bo'lgan barcha ma'lumotlarni ajratib olish

array([[ 0.01403562,  2.37707277, -0.83516992, -1.5142136 ],
       [ 0.07802936, -0.52263526,  0.7971493 ,  0.5713412 ]])

In [9]:
data[names == 'Elyor'] # Elyorga tegishli bo'lgan barcha ma'lumotlarni ajratib olish

array([[ 1.37572648, -1.55586994,  0.2507873 ,  0.65269808],
       [-0.15796344, -0.85404436,  0.60983204,  2.837151  ]])

In [11]:
data[names == 'Hasan', 2:] # Hasaanga tegishli bo'lgan oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[-0.83516992, -1.5142136 ],
       [ 0.7971493 ,  0.5713412 ]])

In [14]:
data[names != 'Hasan'] # Hasandan tashqari barcha insonlarning ma'lumotlarini ajratib olish

array([[ 1.47152496,  1.64142057,  0.14316544, -0.14550955],
       [ 1.988348  , -0.01441726,  0.91414482,  0.54817747],
       [ 1.37572648, -1.55586994,  0.2507873 ,  0.65269808],
       [ 1.0423662 ,  0.97306909,  1.46000477, -0.18628596],
       [-0.15796344, -0.85404436,  0.60983204,  2.837151  ]])

In [15]:
data[~(names == 'Hasan')] # (~) yuqoridagi cell bilan bir xil natija beradi

array([[ 1.47152496,  1.64142057,  0.14316544, -0.14550955],
       [ 1.988348  , -0.01441726,  0.91414482,  0.54817747],
       [ 1.37572648, -1.55586994,  0.2507873 ,  0.65269808],
       [ 1.0423662 ,  0.97306909,  1.46000477, -0.18628596],
       [-0.15796344, -0.85404436,  0.60983204,  2.837151  ]])

In [16]:
print(names)
print(data)

['Hasan' 'Husan' 'Javohir' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[ 0.01403562  2.37707277 -0.83516992 -1.5142136 ]
 [ 1.47152496  1.64142057  0.14316544 -0.14550955]
 [ 1.988348   -0.01441726  0.91414482  0.54817747]
 [ 1.37572648 -1.55586994  0.2507873   0.65269808]
 [ 0.07802936 -0.52263526  0.7971493   0.5713412 ]
 [ 1.0423662   0.97306909  1.46000477 -0.18628596]
 [-0.15796344 -0.85404436  0.60983204  2.837151  ]]


In [24]:
data[(names == 'Hasan') | (names == 'Husan')]

array([[ 0.01403562,  2.37707277, -0.83516992, -1.5142136 ],
       [ 1.47152496,  1.64142057,  0.14316544, -0.14550955],
       [ 0.07802936, -0.52263526,  0.7971493 ,  0.5713412 ]])

In [25]:
data

array([[ 0.01403562,  2.37707277, -0.83516992, -1.5142136 ],
       [ 1.47152496,  1.64142057,  0.14316544, -0.14550955],
       [ 1.988348  , -0.01441726,  0.91414482,  0.54817747],
       [ 1.37572648, -1.55586994,  0.2507873 ,  0.65269808],
       [ 0.07802936, -0.52263526,  0.7971493 ,  0.5713412 ],
       [ 1.0423662 ,  0.97306909,  1.46000477, -0.18628596],
       [-0.15796344, -0.85404436,  0.60983204,  2.837151  ]])

In [26]:
data[data < 0] = 0

In [27]:
data

array([[0.01403562, 2.37707277, 0.        , 0.        ],
       [1.47152496, 1.64142057, 0.14316544, 0.        ],
       [1.988348  , 0.        , 0.91414482, 0.54817747],
       [1.37572648, 0.        , 0.2507873 , 0.65269808],
       [0.07802936, 0.        , 0.7971493 , 0.5713412 ],
       [1.0423662 , 0.97306909, 1.46000477, 0.        ],
       [0.        , 0.        , 0.60983204, 2.837151  ]])