<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/Boolean_indeks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U7')

In [4]:
# data
data = np.random.randn(7,4)
data

array([[ 4.29175134e-01, -2.42941744e+00, -1.19612587e+00,
         1.32359151e+00],
       [ 1.62603502e+00, -7.25770227e-01,  3.68687221e-01,
        -2.19556489e-01],
       [ 3.68564427e-01, -1.89978372e+00,  1.19956390e-01,
         6.36769480e-01],
       [ 1.77265547e+00, -1.35563369e+00,  1.25655520e+00,
        -1.31314618e+00],
       [-4.64617320e-01, -3.87599854e-02,  1.25561878e+00,
        -5.23071825e-01],
       [-5.19736067e-01,  8.90026865e-01, -9.61463424e-02,
        -2.32361225e+00],
       [ 2.15413529e-03, -2.68176945e-02, -9.62647194e-02,
         7.52314033e-01]])

In [5]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [6]:
data[names == 'Hasan'] # Hasanga tegishli bo'lgan barcha ma'lumotlarni ajratib olish

array([[ 0.42917513, -2.42941744, -1.19612587,  1.32359151],
       [-0.46461732, -0.03875999,  1.25561878, -0.52307182]])

In [7]:
data[names == 'Elyor'] # Elyorga tegishli bo'lgan barcha ma'lumotlarni ajratib olish

array([[ 1.77265547, -1.35563369,  1.2565552 , -1.31314618],
       [ 0.00215414, -0.02681769, -0.09626472,  0.75231403]])

In [8]:
data[names == 'Hasan', 2:] # Hasaanga tegishli bo'lgan oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[-1.19612587,  1.32359151],
       [ 1.25561878, -0.52307182]])

In [9]:
data[names != 'Hasan'] # Hasandan tashqari barcha insonlarning ma'lumotlarini ajratib olish

array([[ 1.62603502e+00, -7.25770227e-01,  3.68687221e-01,
        -2.19556489e-01],
       [ 3.68564427e-01, -1.89978372e+00,  1.19956390e-01,
         6.36769480e-01],
       [ 1.77265547e+00, -1.35563369e+00,  1.25655520e+00,
        -1.31314618e+00],
       [-5.19736067e-01,  8.90026865e-01, -9.61463424e-02,
        -2.32361225e+00],
       [ 2.15413529e-03, -2.68176945e-02, -9.62647194e-02,
         7.52314033e-01]])

In [10]:
data[~(names == 'Hasan')] # (~) yuqoridagi cell bilan bir xil natija beradi

array([[ 1.62603502e+00, -7.25770227e-01,  3.68687221e-01,
        -2.19556489e-01],
       [ 3.68564427e-01, -1.89978372e+00,  1.19956390e-01,
         6.36769480e-01],
       [ 1.77265547e+00, -1.35563369e+00,  1.25655520e+00,
        -1.31314618e+00],
       [-5.19736067e-01,  8.90026865e-01, -9.61463424e-02,
        -2.32361225e+00],
       [ 2.15413529e-03, -2.68176945e-02, -9.62647194e-02,
         7.52314033e-01]])

In [11]:
print(names)
print(data)

['Hasan' 'Husan' 'Javohir' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[ 4.29175134e-01 -2.42941744e+00 -1.19612587e+00  1.32359151e+00]
 [ 1.62603502e+00 -7.25770227e-01  3.68687221e-01 -2.19556489e-01]
 [ 3.68564427e-01 -1.89978372e+00  1.19956390e-01  6.36769480e-01]
 [ 1.77265547e+00 -1.35563369e+00  1.25655520e+00 -1.31314618e+00]
 [-4.64617320e-01 -3.87599854e-02  1.25561878e+00 -5.23071825e-01]
 [-5.19736067e-01  8.90026865e-01 -9.61463424e-02 -2.32361225e+00]
 [ 2.15413529e-03 -2.68176945e-02 -9.62647194e-02  7.52314033e-01]]


In [12]:
data[(names == 'Hasan') | (names == 'Husan')]

array([[ 0.42917513, -2.42941744, -1.19612587,  1.32359151],
       [ 1.62603502, -0.72577023,  0.36868722, -0.21955649],
       [-0.46461732, -0.03875999,  1.25561878, -0.52307182]])

In [13]:
data

array([[ 4.29175134e-01, -2.42941744e+00, -1.19612587e+00,
         1.32359151e+00],
       [ 1.62603502e+00, -7.25770227e-01,  3.68687221e-01,
        -2.19556489e-01],
       [ 3.68564427e-01, -1.89978372e+00,  1.19956390e-01,
         6.36769480e-01],
       [ 1.77265547e+00, -1.35563369e+00,  1.25655520e+00,
        -1.31314618e+00],
       [-4.64617320e-01, -3.87599854e-02,  1.25561878e+00,
        -5.23071825e-01],
       [-5.19736067e-01,  8.90026865e-01, -9.61463424e-02,
        -2.32361225e+00],
       [ 2.15413529e-03, -2.68176945e-02, -9.62647194e-02,
         7.52314033e-01]])

In [14]:
data[data < 0] = 0

In [15]:
data

array([[0.42917513, 0.        , 0.        , 1.32359151],
       [1.62603502, 0.        , 0.36868722, 0.        ],
       [0.36856443, 0.        , 0.11995639, 0.63676948],
       [1.77265547, 0.        , 1.2565552 , 0.        ],
       [0.        , 0.        , 1.25561878, 0.        ],
       [0.        , 0.89002686, 0.        , 0.        ],
       [0.00215414, 0.        , 0.        , 0.75231403]])

In [19]:
massiv = np.random.randint(9, size=(3, 3))
massiv.shape

(3, 3)

In [31]:
matrix = np.array([[[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]],

               [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]],

               [[18, 19, 20],
                [21, 22, 23],
                [24, 25, 26]]])

matrix.shape

(3, 3, 3)

In [60]:
result = matrix[1, 1:, :2]
result

array([[12, 13],
       [15, 16]])

In [67]:
new_names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
new_names

array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U7')

In [68]:
new_data = np.array([[5, 6, 1, 1],
   [9, 1, 1, 1],
   [7, 7, 4, 2],
   [1, 5, 1, 9],
   [9, 9, 4, 5],
   [7, 5, 9, 6],
   [5, 3, 7, 4]])
new_data

array([[5, 6, 1, 1],
       [9, 1, 1, 1],
       [7, 7, 4, 2],
       [1, 5, 1, 9],
       [9, 9, 4, 5],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])

In [73]:
mask = (new_names == 'Javohir') | (new_names == 'Elyor')
mask

array([False, False,  True,  True, False,  True,  True])

In [74]:
new_data[mask]

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])