<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/datat_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [ ]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

In [ ]:
# Bir turdagi ma'lumot turidan boshqasiga o'girish
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
data = np.array([1.4, 2.5, 3.6, 4.9])
data.dtype

dtype('float64')

In [ ]:
data

array([1.4, 2.5, 3.6, 4.9])

In [ ]:
int_data = data.astype(np.int64)
int_data.dtype

dtype('int64')