<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/indekslash_and_kesibolish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
arr[-3]

70

In [11]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [12]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [13]:
# copy to copy
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
sliced_arr = arr1[3:5].copy()
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [16]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
# 2 o'lchamli (2d array) massivlarda indeks va kesib olish
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2d[2, 1]

8

In [24]:
arr2d[:2, 1]

array([2, 5])

In [27]:
arr2d[2]

array([7, 8, 9])

In [28]:
# 3-o'lchamli massivlarda indeks va kesib olish asoslari
arr3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [36]:
arr3d[1][1, 1]

13