<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/list_and_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing numpy
import numpy as np

In [ ]:
my_list = list(range(100_000)) # python list 0~99999 --> Normal
my_array = np.array(range(100_000)) # numpy array(massiv) 0~99999 --> Vektorlashgan

In [ ]:
my_array

array([    0,     1,     2, ..., 99997, 99998, 99999])

2.1.1 N-o'lchamli massiv (array)larga ishlov berish


Numpyda massiv yaratishning eng oson yo'llaridan biri bu array fuksiyasi yordamida amalga oshiriladi. Va ushbu funksiya har qanday turdagi ketma-ket ma'lumotlarni qabul qilib, uni yangi Numpy arrayiga o'girib beradi.

In [ ]:
data1 = [1, 2.3, 4, 5] # list
arr1 = np.array(data1) # array

In [ ]:
arr1

array([1. , 2.3, 4. , 5. ])

In [ ]:
data2 = (1, 2, 3.4, 5)
arr2 = np.array(data2)

In [ ]:
arr2

array([1. , 2. , 3.4, 5. ])

In [ ]:
arr1.ndim # array 1 ning o'lchami

1

In [ ]:
arr2.ndim # array 2 ning o'lchami

1

ikki va unda katta o'lchamli massivlar

In [ ]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # list ichidagi list (nested list)
arr3 = np.array(data3)

In [ ]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
massiv = [
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
]
arr4 = np.array(massiv)

In [ ]:
arr4.ndim

3

**shape**, **size** metodlari

In [ ]:
# shape metodi massivning qator va ustunlar sonini ko'rsatadi,
# size metodi massivdagi elementlar sonini ko'rsatadi

arr3.shape

(2, 4)

In [ ]:
arr3.size

8

N-o'lchamli massivni yaratishning boshqa usullari

**zeros** va **ones** fuksiyasi yordamida massivlar yaratish

In [ ]:
arr5 = np.zeros((2, 4)) # barcha elementlari 0 ga teng bo'lgan (2, 4) massiv
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr6 = np.ones((2, 4)) # barcha elementlari 1 ga teng bo'lgan (2, 4) massiv
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**arrange** fuksiyasi yordamida yaratish

In [ ]:
arr7 = np.arange(4, 20, 2) # 4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr8 = np.arange(20) # 0 dan 20 gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr9 = np.random.rand(2, 4) # (2, 4) o'lchamli --> (0 ~ 1) taxminiy qiymatlardan tashkil topadi
arr9

array([[0.12135652, 0.25715826, 0.71893767, 0.95513011],
       [0.83175993, 0.46982631, 0.80428583, 0.6378168 ]])

In [ ]:
arr10 = np.random.randint(5, size=(5)) # (2, 4) o'lchamli va max qiymati 5 bo'lgan int sonlar
arr10

array([0, 3, 4, 4, 2])

In [ ]:
arr11 = np.random.randn(2, 4) # (2, 4) o'lchamli --> elementlari (Norm dist)
arr11

array([[ 1.13204962, -1.42987244,  1.86644192, -0.02052022],
       [-0.77125722,  0.95602835, -0.56689819,  1.39685382]])