<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/logic_operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Massiv
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [3]:
# condition
cond = np.array([True, False, True, True, False])

In [5]:
# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [7]:
arr = np.random.randn(4, 4)
arr

array([[-0.53073238,  0.01309679,  0.7988307 ,  1.09797095],
       [-1.09353901,  3.08896049, -1.57570497,  1.07732863],
       [ 0.40577844, -0.53283383, -0.12737217,  0.6716958 ],
       [-0.58315717,  0.17687328,  1.11348924, -1.91162534]])

In [8]:
results = np.where(arr < 0, -2, 2)
results

array([[-2,  2,  2,  2],
       [-2,  2, -2,  2],
       [ 2, -2, -2,  2],
       [-2,  2,  2, -2]])

In [10]:
results = np.where(arr > 1, 1, -1)
results

array([[-1, -1, -1,  1],
       [-1,  1, -1,  1],
       [-1, -1, -1, -1],
       [-1, -1,  1, -1]])