<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/Maths%26Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# data
arr = np.random.randn(5, 4) # (5, 4) o'lchovli massiv
arr

array([[ 0.01653823,  0.64528909, -0.25227234, -1.01434461],
       [-1.29390566, -0.18790655,  0.97052185, -2.06565895],
       [ 0.05395094, -0.28827085, -1.15592559,  1.42126992],
       [ 0.92971379, -1.53830513,  0.43427869, -1.65455547],
       [-0.86865819, -0.56343249, -0.045513  , -2.07785386]])

In [6]:
# sum methodi
arr.sum() # massiv ichidagi barcha elementlarning yig'indisini hisoblab beradi

-8.535040181955683

In [8]:
np.sum(arr) # arr ning barcha elementlarining yig'indisini hisoblab beradi

-8.535040181955683

In [10]:
arr.sum(axis=1) # qator yig'indisi

array([-0.60478963, -2.57694932,  0.03102442, -1.82886812, -3.55545754])

In [11]:
arr.sum(axis=0) # ustun yig'indisi

array([-1.16236089, -1.93262593, -0.04891038, -5.39114298])

In [13]:
# mean methodi

# sodda data
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [14]:
mean = np.sum(data) / len(data)
mean

2.0

In [15]:
np.mean(data)

2.0

In [16]:
data.mean()

2.0

In [17]:
arr

array([[ 0.01653823,  0.64528909, -0.25227234, -1.01434461],
       [-1.29390566, -0.18790655,  0.97052185, -2.06565895],
       [ 0.05395094, -0.28827085, -1.15592559,  1.42126992],
       [ 0.92971379, -1.53830513,  0.43427869, -1.65455547],
       [-0.86865819, -0.56343249, -0.045513  , -2.07785386]])

In [18]:
np.mean(arr)

-0.42675200909778416

In [19]:
np.mean(arr, axis=1) # qator bo'yicha o'rtacha qiymatni qaytaradi

array([-0.15119741, -0.64423733,  0.0077561 , -0.45721703, -0.88886438])

In [20]:
np.mean(arr, axis=0) # ustun bo'yicha o'rtacha qiymatni qaytaradi

array([-0.23247218, -0.38652519, -0.00978208, -1.0782286 ])

In [21]:
# cumsum methodi
data

array([0, 1, 2, 3, 4])

In [22]:
data.cumsum()

array([ 0,  1,  3,  6, 10])