<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
# data
arr = np.random.rand(4)
arr

array([0.55493094, 0.83210455, 0.16615714, 0.85777957])

In [7]:
# 1 usul
sorted_arr = np.sort(arr)
sorted_arr

array([0.16615714, 0.55493094, 0.83210455, 0.85777957])

In [8]:
# 2 usul
arr.sort()
arr

array([0.16615714, 0.55493094, 0.83210455, 0.85777957])

In [10]:
# teskari tartiblash
rev_arr = -np.sort(-arr)
rev_arr

array([0.85777957, 0.83210455, 0.55493094, 0.16615714])

In [11]:
# 2D array (massiv)
arr2d = np.random.randn(2, 4)
arr2d

array([[ 0.60922743,  0.58147617,  0.15868468,  0.6891862 ],
       [-0.20467999, -2.31740312, -1.13346411, -0.45592696]])

In [12]:
# axis = 0 --> Qator
row_srt = np.sort(arr2d, axis=0) # arr2d ning xar bir qatori bo'yicha tartiblangan ko'rinishi
row_srt

array([[-0.20467999, -2.31740312, -1.13346411, -0.45592696],
       [ 0.60922743,  0.58147617,  0.15868468,  0.6891862 ]])

In [13]:
# axis = 1 --> Ustun
col_srt = np.sort(arr2d, axis=1) # arr2d ning xar bir ustun bo'yicha tartiblangan ko'rinishi
col_srt

array([[ 0.15868468,  0.58147617,  0.60922743,  0.6891862 ],
       [-2.31740312, -1.13346411, -0.45592696, -0.20467999]])