<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# sqrt massivning har bir elementini kvadrat ildizini qaytaradi
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
# square massivning har bir elementini kvadratga oshiradi
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
# exp massivning har bir elementini exponentini qaytaradi
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
# log massivning har bir logorifmini hisoblaydi
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
# modf bu funksiya haqiqiy sonlarini qoldiq va butun qismini ajratib beradi
arr1 = np.random.randn(6)
arr1

array([-0.94551495,  1.246226  ,  1.04063204,  0.116798  , -0.51693957,
       -1.46620222])

In [ ]:
qoldiq, butun = np.modf(arr1)

In [ ]:
print(qoldiq)
print(butun)

[-0.94551495  0.246226    0.04063204  0.116798   -0.51693957 -0.46620222]
[-0.  1.  1.  0. -0. -1.]


In [ ]:
# sign funkisiyasi massiv elementlarining qiymati manfiy bo'lsa -1 aksincha musbat bo'lsa 1 ni qaytaradi
np.sign(arr1)

array([-1.,  1.,  1.,  1., -1., -1.])

In [ ]:
# isnan massivning elementlarida NaN ma'lumoti bo'lsa True qaytaradi va aksincha esa False qaytaradi
arr1

array([-0.94551495,  1.246226  ,  1.04063204,  0.116798  , -0.51693957,
       -1.46620222])

In [ ]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [ ]:
arr1[0] = np.NaN
arr1

array([        nan,  1.246226  ,  1.04063204,  0.116798  , -0.51693957,
       -1.46620222])

In [ ]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

In [ ]:
# Binary functions

In [ ]:
# 2 ta massivnin yaratib olamiz
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [ ]:
arr2

array([ 0.13283304, -0.39464737, -1.26837396,  1.90530314, -0.06613996,
       -0.84828497])

In [ ]:
arr3

array([-0.80079764,  0.00464564, -1.28620005,  0.35211115,  0.12561714,
        0.07301564])

In [26]:
np.add(arr2, arr3) # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi

array([-0.6679646 , -0.39000173, -2.55457401,  2.25741429,  0.05947718,
       -0.77526933])

In [27]:
arr2 + arr3

array([-0.6679646 , -0.39000173, -2.55457401,  2.25741429,  0.05947718,
       -0.77526933])