<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/working_with_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
# reshape() method
A = np.arange(6).reshape(3, 2) # A massiv: Elementlari 0~6 gacha bo'lgan, shape (3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.T # A massivning Transpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [7]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
A.swapaxes(1, 0) # A massivning Transpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
np.dot(A, A.T) # AxA^T hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])