<a href="https://colab.research.google.com/github/yusufbek-murodov/Test/blob/main/working_with_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('data', arr)

In [5]:
arr2 = np.load('data.npy')

In [6]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1 = np.arange(20)

In [10]:
np.savez('arrays', a=arr, b=arr1)

In [12]:
arrays = np.load('arrays.npz')

In [13]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.savez_compressed('array_comp.npz', a=arr, b=arr1)